apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-service
  template:
    metadata:
      labels:
        app: token-service
    spec:
      containers:
      - name: token-service
        image: enzokpo123/token-service:latest
        ports:
        - containerPort: 8001
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_URL
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_USER
          - name: DATABASE_PASS
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_PASS
