server:
  port: 8080
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance: localhost
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: main-server
         uri: lb://main-server
         predicates:
           - Path=/api/**
       