apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
      - name: main-server
        image: enzokpo123/main-server:latest
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_URL
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_USER
          - name: DATABASE_PASS
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_PASS
