server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heinzex/backend-gestion-ml
          password: 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
          search-paths: config-data
          default-label: master

  application:
    name: config-server
          
