server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/heinzex/backend-gestion-ml
          search-paths: config-data
          username: heinzex
          password: 6185961858Enzo
  application:
    name: config-server
          
