apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
      - name: gateway-server
        image: enzokpo123/gateway-server:latest
        ports:
        - containerPort: 8080
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_URL
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_USER
          - name: DATABASE_PASS
            valueFrom:
              configMapKeyRef:
                name: env
                key: DATABASE_PASS
